/**
 * AUTO-GENERATED — do not edit by hand. Source: `tokens/tokens.json` (DTCG 2025.10–shaped).
 * Run `yarn generate:design-tokens`, `yarn build`, or `yarn build:truss`.
 */

export const Tokens = {
  ButtonCautionDisabledBg: "--b-button-caution-disabled-bg",
  ButtonCautionDisabledFg: "--b-button-caution-disabled-fg",
  ButtonDangerDisabledBg: "--b-button-danger-disabled-bg",
  ButtonDangerDisabledFg: "--b-button-danger-disabled-fg",
  ButtonGhostDisabledFg: "--b-button-ghost-disabled-fg",
  ButtonGhostFg: "--b-button-ghost-fg",
  ButtonPrimaryDisabledBg: "--b-button-primary-disabled-bg",
  ButtonPrimaryDisabledFg: "--b-button-primary-disabled-fg",
  ButtonTertiaryFg: "--b-button-tertiary-fg",
  ButtonTertiaryFgPressed: "--b-button-tertiary-fg-pressed",
  Danger: "--b-danger",
  DangerPressed: "--b-danger-pressed",
  EnvBrandDev: "--b-env-brand-dev",
  EnvBrandLocalProd: "--b-env-brand-local-prod",
  EnvBrandProd: "--b-env-brand-prod",
  EnvBrandQa: "--b-env-brand-qa",
  FieldBgDefault: "--b-field-bg-default",
  FieldBgDisabled: "--b-field-bg-disabled",
  FieldBgHover: "--b-field-bg-hover",
  FieldBorderDefault: "--b-field-border-default",
  FieldBorderError: "--b-field-border-error",
  FieldBorderFocus: "--b-field-border-focus",
  FieldBorderHover: "--b-field-border-hover",
  FieldTextDisabled: "--b-field-text-disabled",
  FocusRingInset: "--b-focus-ring-inset",
  FocusRingMuted: "--b-focus-ring-muted",
  ListRowBgHover: "--b-list-row-bg-hover",
  LoaderFill: "--b-loader-fill",
  LoaderSpinner: "--b-loader-spinner",
  LoaderTrack: "--b-loader-track",
  MenuItemBgHover: "--b-menu-item-bg-hover",
  NavItemBgActive: "--b-nav-item-bg-active",
  NavItemBgHover: "--b-nav-item-bg-hover",
  NavItemBgPressed: "--b-nav-item-bg-pressed",
  NavText: "--b-nav-text",
  NavTextActive: "--b-nav-text-active",
  NavTextDisabled: "--b-nav-text-disabled",
  NavTextFocusVisible: "--b-nav-text-focus-visible",
  NavTextPressed: "--b-nav-text-pressed",
  NeutralFillHoverStrong: "--b-neutral-fill-hover-strong",
  NeutralFillHoverSubtle: "--b-neutral-fill-hover-subtle",
  NeutralFillPressed: "--b-neutral-fill-pressed",
  NeutralSurfacePressed: "--b-neutral-surface-pressed",
  OnPrimary: "--b-on-primary",
  OnSurface: "--b-on-surface",
  OnSurfaceMuted: "--b-on-surface-muted",
  OnSurfaceSubtle: "--b-on-surface-subtle",
  PopoverSurface: "--b-popover-surface",
  Primary: "--b-primary",
  PrimaryHover: "--b-primary-hover",
  PrimaryPressed: "--b-primary-pressed",
  Scrim: "--b-scrim",
  SelectionIndicator: "--b-selection-indicator",
  StatusSuccessFg: "--b-status-success-fg",
  Surface: "--b-surface",
  SurfaceSeparator: "--b-surface-separator",
  SurfaceSubtle: "--b-surface-subtle",
  TextDisabled: "--b-text-disabled",
  TextHelper: "--b-text-helper",
  TextLabel: "--b-text-label",
  TextLinkDefault: "--b-text-link-default",
  TextLinkDisabled: "--b-text-link-disabled",
  TextLinkHover: "--b-text-link-hover",
  TextLinkPressed: "--b-text-link-pressed",
  TextPlaceholder: "--b-text-placeholder",
  TextSelection: "--b-text-selection",
} as const;
